# Generated by Django 2.2 on 2019-04-18 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RateFrequency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.CharField(choices=[('W', 'Weekly'), ('B', 'Biweekly'), ('M', 'Monthly')], default='W', max_length=1, verbose_name='Rate')),
            ],
        ),
        migrations.RemoveField(
            model_name='dayfrequency',
            name='rate',
        ),
    ]
