# Generated by Django 2.2 on 2019-04-18 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0002_auto_20190418_1204'),
    ]

    operations = [
        migrations.CreateModel(
            name='Automations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Name')),
                ('day', models.CharField(choices=[('SUN', 'Sunday'), ('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednessday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saterday')], default='SUN', max_length=3, verbose_name='Day')),
                ('rate', models.CharField(choices=[('W', 'Weekly'), ('B', 'Biweekly'), ('M', 'Monthly')], default='W', max_length=1, verbose_name='Rate')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('functionsatcompany', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scrap.FunctionAtComapny')),
                ('geography', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scrap.Geography')),
                ('period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scrap.YearAtCompany')),
                ('srlevel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scrap.SeniorityLevel')),
            ],
        ),
        migrations.DeleteModel(
            name='DayFrequency',
        ),
        migrations.DeleteModel(
            name='RateFrequency',
        ),
    ]
