# Generated by Django 2.2 on 2019-04-18 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0003_auto_20190418_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='automations',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
