# Generated by Django 2.2 on 2019-04-25 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0005_linkedin'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CompanyName', models.CharField(blank=True, max_length=200, null=True)),
                ('Name', models.CharField(blank=True, max_length=100, null=True)),
                ('SeniorityLevel', models.CharField(blank=True, max_length=100, null=True)),
                ('Function', models.CharField(blank=True, max_length=200, null=True)),
                ('Degree', models.CharField(blank=True, max_length=200, null=True)),
                ('GradYearStart', models.DateTimeField(blank=True, null=True)),
                ('GradYearEnd', models.DateTimeField(blank=True, null=True)),
                ('Url', models.URLField(blank=True, max_length=100, null=True)),
                ('DateOfEntry', models.DateTimeField(auto_now_add=True, null=True)),
                ('IsDuplicated', models.CharField(blank=True, max_length=200, null=True)),
                ('Approve', models.CharField(blank=True, max_length=150, null=True)),
                ('Reject', models.CharField(blank=True, max_length=150, null=True)),
                ('AutomationId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scrap.Automations')),
            ],
        ),
    ]
