# Generated by Django 2.2 on 2019-04-26 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0007_automations_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automations',
            name='status',
            field=models.BooleanField(),
        ),
    ]
