# Generated by Django 2.2 on 2019-04-26 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0008_auto_20190426_0404'),
    ]

    operations = [
        migrations.AddField(
            model_name='automationdata',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='automations',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
