# Generated by Django 2.2 on 2019-05-01 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0010_auto_20190426_0653'),
    ]

    operations = [
        migrations.RenameField(
            model_name='automationdata',
            old_name='AutomationId',
            new_name='automation',
        ),
        migrations.RenameField(
            model_name='automationdata',
            old_name='CompanyName',
            new_name='companyname',
        ),
        migrations.RenameField(
            model_name='automationdata',
            old_name='DateOfEntry',
            new_name='dateofentry',
        ),
        migrations.RenameField(
            model_name='automationdata',
            old_name='Degree',
            new_name='degree',
        ),
        migrations.RenameField(
            model_name='automationdata',
            old_name='Function',
            new_name='function',
        ),
        migrations.RenameField(
            model_name='automationdata',
            old_name='GradYearEnd',
            new_name='gradyearend',
        ),
        migrations.RenameField(
            model_name='automationdata',
            old_name='GradYearStart',
            new_name='gradyearstart',
        ),
        migrations.RenameField(
            model_name='automationdata',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='automationdata',
            old_name='SeniorityLevel',
            new_name='senioritylevel',
        ),
        migrations.RenameField(
            model_name='automationdata',
            old_name='Url',
            new_name='url',
        ),
        migrations.RemoveField(
            model_name='automationdata',
            name='Approve',
        ),
        migrations.RemoveField(
            model_name='automationdata',
            name='IsDuplicated',
        ),
        migrations.RemoveField(
            model_name='automationdata',
            name='Reject',
        ),
        migrations.AddField(
            model_name='automationdata',
            name='isduplicated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='automationdata',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('A', 'Approve'), ('R', 'Reject')], default='P', max_length=1, verbose_name='Status'),
        ),
    ]
