# Generated by Django 2.2 on 2019-05-03 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0012_auto_20190503_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automationdata',
            name='status',
            field=models.CharField(blank=True, choices=[('P', 'Pending'), ('A', 'Approve'), ('R', 'Reject')], default='P', max_length=1, null=True, verbose_name='Status'),
        ),
    ]
