# Generated by Django 2.2 on 2019-05-04 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0013_auto_20190503_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automationdata',
            name='gradyearend',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='automationdata',
            name='gradyearstart',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
