# Generated by Django 2.2 on 2019-05-04 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0014_auto_20190504_0453'),
    ]

    operations = [
        migrations.AddField(
            model_name='automationdata',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scrap.LinkedIn'),
        ),
    ]
