# Generated by Django 2.2 on 2019-05-17 08:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0017_auto_20190517_0813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automationdata',
            name='entry_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 5, 17, 8, 24, 27, 25238, tzinfo=utc), null=True),
        ),
    ]
