# Generated by Django 2.2 on 2019-05-17 09:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0023_auto_20190517_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automationdata',
            name='entry_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
