# Generated by Django 2.2 on 2019-05-17 09:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0028_auto_20190517_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automationdata',
            name='entry_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 5, 17, 9, 39, 2, 752906)),
        ),
    ]
