# Generated by Django 2.2 on 2019-05-17 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0029_auto_20190517_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='automationdata',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='automationdata',
            name='entry_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
