# Generated by Django 2.2 on 2019-05-17 11:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0030_auto_20190517_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automations',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 17, 11, 4, 51, 676236)),
        ),
    ]
