# Generated by Django 2.2 on 2019-05-17 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0031_auto_20190517_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automations',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
