# Generated by Django 2.2 on 2019-05-17 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0032_auto_20190517_1108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='automationdata',
            name='entry_date',
        ),
        migrations.RemoveField(
            model_name='automationdata',
            name='updated',
        ),
    ]
