# Generated by Django 2.2 on 2019-05-22 11:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0033_auto_20190517_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automations',
            name='rate',
            field=models.CharField(choices=[('W', 'Weekly'), ('M', 'Monthly')], default='W', max_length=1, verbose_name='Rate'),
        ),
        migrations.CreateModel(
            name='Cron',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('execution_type', models.CharField(default='cron', max_length=200)),
                ('is_active', models.BooleanField(blank=True, default=False, null=True)),
                ('last_exe_date', models.DateField(blank=True, default=django.utils.timezone.now, max_length=200)),
                ('automation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scrap.Automations')),
            ],
        ),
    ]
