# Generated by Django 2.2 on 2019-05-22 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0034_auto_20190522_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cron',
            name='is_active',
            field=models.BooleanField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='cron',
            name='last_exe_date',
            field=models.DateField(blank=True, max_length=200, null=True),
        ),
    ]
