# Generated by Django 2.2 on 2019-05-22 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0036_cron_execution_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cron',
            name='is_active',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
