# Generated by Django 2.2 on 2019-05-27 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0037_auto_20190522_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='automations',
            name='interval',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
