# Generated by Django 2.2 on 2019-05-27 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0038_automations_interval'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='automations',
            name='interval',
        ),
    ]
