# Generated by Django 2.2 on 2019-05-27 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0039_remove_automations_interval'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScriptInterval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interval', models.DateTimeField(auto_now_add=True, null=True)),
                ('automation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scrap.Automations')),
            ],
        ),
    ]
