# Generated by Django 2.2 on 2019-06-05 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0041_auto_20190527_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automationdata',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='scriptinterval',
            name='interval',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
