# Generated by Django 2.2 on 2019-06-22 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0042_auto_20190605_1725'),
    ]

    operations = [
        migrations.CreateModel(
            name='YearofExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True, verbose_name='Title')),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, unique=True)),
            ],
        ),
    ]
