# Generated by Django 2.2 on 2019-06-22 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0043_yearofexperience'),
    ]

    operations = [
        migrations.AddField(
            model_name='automations',
            name='yearsofexperience',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='scrap.YearofExperience'),
        ),
        migrations.AlterField(
            model_name='automations',
            name='functionsatcompany',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='scrap.FunctionAtComapny'),
        ),
        migrations.AlterField(
            model_name='automations',
            name='geography',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='scrap.Geography'),
        ),
        migrations.AlterField(
            model_name='automations',
            name='period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='scrap.YearAtCompany'),
        ),
        migrations.AlterField(
            model_name='automations',
            name='srlevel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='scrap.SeniorityLevel'),
        ),
    ]
