# Generated by Django 2.2 on 2019-06-22 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0044_auto_20190622_0629'),
    ]

    operations = [
        migrations.AddField(
            model_name='automations',
            name='functionsatcompanyl_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='automations',
            name='geography_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='automations',
            name='period_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='automations',
            name='srlevel_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='automations',
            name='yearsofexperience_status',
            field=models.BooleanField(default=True),
        ),
    ]
