# Generated by Django 2.2 on 2019-06-27 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0045_auto_20190622_0806'),
    ]

    operations = [
        migrations.AddField(
            model_name='scriptinterval',
            name='running',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
